version: '3.1'

services:
  db:
    image: 'postgres:10-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  # redis:
  #   image: 'redis:5-alpine'
  #   command: redis-server
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - 'redis:/data'

  # sidekiq_web:
  #   image: aschzero/sidekiq-web
  #   environment:
  #     REDIS_URL: redis://redis:6379
  #     # SIDEKIQ_USER: myusername
  #     # SIDEKIQ_PASSWORD: password123
  #   ports:
  #     - '3030:3030'

  # bundle_cache:
  #   image: 'busybox'
  #   volumes:
  #     - 'bundle_cache:/bundle_cache'

  adminer:
    image: 'adminer'
    ports:
      - '8080:8080'

volumes:
  redis:
  postgres:
  bundle_cache:
